name: metaproxy

services:
  metaproxy:
    image: metaproxy
    build:
      context: ./metaproxy
      dockerfile: Dockerfile
    ports:
        - "5005:5000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "5006:5000"

  db:
    image: mysql:5.5.54
    environment:
      MYSQL_ROOT_PASSWORD: 100%db
      MYSQL_DATABASE: NeuMO
    volumes:
      - /data/dbs/gmu/NeuMO:/var/lib/mysql
    ports:
      - "3306:3306"
