name: metaproxy

services:
  metaproxy:
    image: metaproxy
    build:
      context: ./metaproxy
      dockerfile: Dockerfile
    ports:
        - "5005:5000"
  backend:
    image: neuromorpho/summaryreporting-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "5006:5000"
    env_file:
        - ./backend/.env
    networks:
        default:
        similarity-search_default:
    external_links:
        - "similarity-search-mysql-1:db"

networks:
    similarity-search_default:
        external: true
